#!/usr/bin/env bash

function bootstrap {
  if ! pkg ensure sysutils/daemontools; then
    mkdir -p "$WRKOBJDIR/sysutils/daemontools/work/.destdir/$HOME/install/bin"
    touch "$WRKOBJDIR/sysutils/daemontools/work/.destdir/$HOME/install/bin/svscanboot"
    pkg ensure sysutils/daemontools
  fi

  rsync -ia $PKGWIPDIR/runit/. $PKGSRCDIR/sysutils/runit/.
  if ! pkg ensure sysutils/runit; then
    perl -pe 's{-static}{}' -i "$WRKOBJDIR/sysutils/runit/work/admin/runit-2.0.0/src/Makefile"
    pkg ensure sysutils/runit
  fi
}

bootstrap
