#!/usr/bin/env bash

function bootstrap {
  pkg ensure sysutils/daemontools

	case "${DISTRIB_ID}" in
		Darwin)
			brew install runit
			;;
		Ubuntu)
			${NOSUDO} sudo -E apt-get install -y runit
			;;
		Amazon)
			echo "WTF"
			;;
	esac
}

bootstrap
